# Generated by Django 3.1.7 on 2021-03-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.FloatField(help_text='Unix time in milliseconds')),
                ('lastModificationDate', models.FloatField(help_text='Unix time in milliseconds')),
                ('timestamp', models.FloatField(help_text='Unix time in milliseconds')),
                ('value1', models.CharField(max_length=200)),
                ('value2', models.FloatField()),
                ('value3', models.BooleanField(default=False)),
            ],
        ),
    ]
